#!bin/bash
while:
do
wget ""
domains(){
    mkdir subdomains
    unzip -o "" -d /root/$domain/subdomains
    rm -r ""
}
domains

cat /root/subdomains/*.null.* > subdomains_list.txt
cat subdomains_list.txt | anew baseline_subdomain.txt > added_subdomains.txt 
sleep 1min
cat added_subdomains.txt | notify

sleep 24h
done
